[project]
name = "ModLibrary"
version = "0.0.1dev1"
description = "A Minecraft mod manager"

[tool.distutils.build_exe]
excludes = ["unittest"]
zip_include_packages = ["encodings"]
include_files = ["LICENSE", "mods.json", "pyproject.toml", "requirements.txt", "settings.json", "lang/"]
