name: Python CI with compile on Linux

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[build.skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Copy pack resources into pack folder
      run: |
        cp -pr pack-resources/common dist/
    - name: Setup Python 3.11
      uses: actions/setup-python@v4.5.0
      with: 
        python-version: "3.11"
    - name: Build with compileall
      run: |
        python -m compileall . -l -o 2
        cp -pr __pycache__/* dist/
        cd dist
        man rename
        cd ..
    - name: Get latest commit hash
      id: get_hash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ModLibrary-PYC-${{ steps.get_hash.outputs.sha_short }}
        path: dist/
