name: Python CI with compile

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[build.skip]')"
    steps:
    - uses: actions/checkout@v3
    - name: Prepare build.
      run: |
        mkdir dist
        cd dist
        mkdir runtime
        cd..
        cd..
    - name: Set up Python 3.10
      uses: gamedev-thingy/Download-Extract@done
      with:
        url: https://www.python.org/ftp/python/3.11.2/python-3.11.2-embed-win32.zip
        destination: ./dist/runtime
        ZIPname: python_embed_runtime_win32
    - name: Install dependencies
      run: |
        ./dist/runtime/python.exe -m pip install --upgrade pip
        ./dist/runtime/python.exe -m pip install -r requirements.txt
    - name: Build with compileall
      run: |
        python -m compileall . -l -o 2
        cd __pycache__
        set "str=.cpython-310.opt-2"
        setlocal EnableDelayedExpansion
        for /f "delims=" %%i in ('dir /b *.cpython-310.opt-2.pyc') do (
        set "var=%%i" & ren "%%i" "!var:%str%=!")
        cd ..
        xcopy __pycache__ dist\ /E /Y
    - name: Get latest commit hash
      id: get_hash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ModLibrary-PYC-${{ steps.get_hash.outputs.sha_short }}
        path: dist\
